### ISSUE TITLE
question regarding the anchors

### ISSUE THREAD

**Issue by aliechoes** [lkmklsmn/insct#6]
Hi Lukas

thanks for the nice work. I have a question.

In your work, is it assumed that the "label" of the cells are provided? For example if I have Batch1 cell type 1 & 2, do I know this information beforehand?

cheers
Ali

**Comment by lkmklsmn** [comment]
Hi Ali,

Thanks for your interest!

In the unsupervised mode the "cell type" labels are not provided. Instead, the labels are inferred using a combination of KNN and [MNN](https://www.nature.com/articles/nbt.4091) based on PCs derived from gene expression. The batch "label", however, needs to be provided. For example, check this [code](https://colab.research.google.com/drive/1LEDnRwFH2v166T-pUaCYb6TZMgfViO-W?usp=sharing).

In the supervised and semi-supervised mode the "cell type" labels can we provided to increase accuracy.  For example, check this [code](https://colab.research.google.com/drive/1Ulj0ghqdRMjedUQKHECyoQQyl8j4tdJF?usp=sharing).

Best,

Lukas
