### ISSUE TITLE
Does INSCT require cell type labels known to perform any integration?

### ISSUE THREAD

**Issue by chansigit** [lkmklsmn/insct#8]
Dear authors, 
Thank you for your work. I wonder if INSCT must have cell type labels to align multiple batches together? 

It is often difficult to judge whether clusters from two batches are literally the same identity.

can we run INSCT without cell type informations?

**Comment by lkmklsmn** [comment]
Hi @chansigit ,

Thanks for your interest!

Yes, you can run insct without cell type labels!

Pls check this [example](https://colab.research.google.com/drive/1LEDnRwFH2v166T-pUaCYb6TZMgfViO-W?usp=sharing)  for more info.

**Comment by chansigit** [comment]
thanks for your rapid responses!  That would be wonderful.

But I still wonder why. the triplet losses need cells of the same type as positive-anchor pairs, and cells of different batches as negative-anchor pairs. Without cell-type labels, how does the algorithm optimize the triplet losses?

**Comment by lkmklsmn** [comment]
Good question!

In this case we first estimate cell similarity based on KNN and MNN. Then we define positive-anchor pairs as cells within either KNN or MNN. So we learn the labels like that and then optimize triplet loss. 

This idea was first described in this [paper](https://www.nature.com/articles/s41598-019-45301-0) (as far as I know) .

You are absolutely correct that triplet loss needs labels!

**Comment by chansigit** [comment]
Thank you very much! :D
